### ISSUE TITLE
How can I use it with webpack?

### ISSUE THREAD

**Issue by shilik** [fasiha/kamiya-codec#1]
Hi, @fasiha 

I just wonder is it possible to make your code work with webpack?

I got the following errors:
ERROR in ../node_modules/kamiya-codec/index.js
Module not found: Error: Can't resolve './hiragana' in '/Users/mac/jlptthree2/node_modules/kamiya-codec'
 @ ../node_modules/kamiya-codec/index.js 15:19-40
 @ ../node_modules/babel-loader/lib!../node_modules/vue-loader/lib??vue-loader-options!./components/Home.vue?vue&type=script&lang=js&
 @ ./components/Home.vue?vue&type=script&lang=js&
 @ ./components/Home.vue
 @ ./main.js

then, I modified the index.js to make ./hiragana into ./hiragana.ts
but the result turned out with no luck.

 ERROR in ../node_modules/kamiya-codec/hiragana.ts 1:16
Module parse failed: Unexpected token (1:16)
You may need an appropriate loader to handle this file type.
> const split = (s: string) => s.split('');
| const vec = [
|   split('あいうえお'),
 @ ../node_modules/kamiya-codec/index.js 15:19-43
 @ ../node_modules/babel-loader/lib!../node_modules/vue-loader/lib??vue-loader-options!./components/Home.vue?vue&type=script&lang=js&
 @ ./components/Home.vue?vue&type=script&lang=js&
 @ ./components/Home.vue
 @ ./main.js

Any suggestion?

Shilik

**Comment by shilik** [comment]
Hi,@fasiha,
Thank you for the quick response.
It works like a charm after following your suggestion.
With your generous help, I can move on to the next step on my project!
Thank you very much!
By the way, your module works only on verbs, would you consider integrating nouns as well as adjectives into your module?  It should be easier to deal with nouns and i-adjectives/na-adjectives, as the rules are relatively fewer than verbs.
I think Japanese learners will benifit a lot from your module if the above is included. :)

Shilik

**Comment by fasiha** [comment]
I added the transpiled JavaScript to the npm module, so Webpack (and everything else using JavaScript) should work!!! Thank you so much for using my module!
