### ISSUE TITLE
loop for all possbile combination

### ISSUE THREAD

**Issue by shilik** [fasiha/kamiya-codec#2]
Hi, fasha,

I tried to use loops to get all possbile combinations of a verb.
But I noticed that Auxiliary or Conjugation properties like codec.Auxiliary.SeruSaseru, codec.Conjugation.Conditional  are not STRINGs, 
I have put either "codec.Auxiliary.SeruSaseru" or codec.Auxiliary.SeruSaseru in an array.
but none of the above worked.

Do you have any suggestions for looping out all combinations of a verb without having to hard-code everything?

**Comment by fasiha** [comment]
For future visitors, this is one way you can do this in pure JavaScript, where TypeScript's enums are treated as numbers:
```js
'use strict';
var codec = require('./index');
var v = '書く';
for (var iaux = 0, aux = codec.Auxiliary[iaux]; aux = codec.Auxiliary[iaux]; iaux++) {
  for (var icon = 0, conj = codec.Conjugation[icon]; conj = codec.Conjugation[icon]; icon++) {
    var res = 'xxx';
    try {
      res = codec.conjugateAuxiliary(v, iaux, icon).join(' / ');
    } catch (e) {}
    console.log(aux, conj, res);
  }
}
```
Note how `codec.Conjugation[0]` is `"Negative"`, while `codec.Conjugation.Negative` is `0`, and it's this latter, `0`, that you want to pass into `codec.conjugateAuxiliary` or `codec.conjugateTypeI` etc.

Thanks for posting this, I should be better about using my TypeScript libraries from JavaScript. Not enough hours in the day.
